//
// SubscriptionAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SubscriptionAPI: APIBase {
    /**
     Create a subscription for a device for a user
     
     - parameter userId: (path) The id (UUID) of the user to create a device for.  
     - parameter deviceId: (path) The id (UUID) of the user device.  
     - parameter subscription: (body) Subscription to create on a device.  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createSubscription(userId: String, deviceId: String, subscription: Subscription, completion: @escaping ((_ data: Subscription?,_ error: Error?) -> Void)) {
        createSubscriptionWithRequestBuilder(userId: userId, deviceId: deviceId, subscription: subscription).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create a subscription for a device for a user
     - POST /users/{userId}/devices/{deviceId}/subscriptions
     - examples: [{contentType=application/json, example={
  "duration" : 1.4658129805029452,
  "createdAt" : 0,
  "topic" : "aeiou",
  "range" : 6.027456183070403,
  "selector" : "aeiou",
  "pushers" : [ "aeiou" ],
  "id" : "aeiou",
  "deviceId" : "aeiou"
}}]
     
     - parameter userId: (path) The id (UUID) of the user to create a device for.  
     - parameter deviceId: (path) The id (UUID) of the user device.  
     - parameter subscription: (body) Subscription to create on a device.  

     - returns: RequestBuilder<Subscription> 
     */
    open class func createSubscriptionWithRequestBuilder(userId: String, deviceId: String, subscription: Subscription) -> RequestBuilder<Subscription> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = subscription.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Subscription>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete a Subscription
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteSubscription(userId: String, deviceId: String, subscriptionId: String, completion: @escaping ((_ error: Error?) -> Void)) {
        deleteSubscriptionWithRequestBuilder(userId: userId, deviceId: deviceId, subscriptionId: subscriptionId).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Delete a Subscription
     - DELETE /users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}
     - 
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 

     - returns: RequestBuilder<Void> 
     */
    open class func deleteSubscriptionWithRequestBuilder(userId: String, deviceId: String, subscriptionId: String) -> RequestBuilder<Void> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{subscriptionId}", with: "\(subscriptionId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Info about a subscription on a device of a user
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSubscription(userId: String, deviceId: String, subscriptionId: String, completion: @escaping ((_ data: Subscription?,_ error: Error?) -> Void)) {
        getSubscriptionWithRequestBuilder(userId: userId, deviceId: deviceId, subscriptionId: subscriptionId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Info about a subscription on a device of a user
     - GET /users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}
     - examples: [{contentType=application/json, example={
  "duration" : 1.4658129805029452,
  "createdAt" : 0,
  "topic" : "aeiou",
  "range" : 6.027456183070403,
  "selector" : "aeiou",
  "pushers" : [ "aeiou" ],
  "id" : "aeiou",
  "deviceId" : "aeiou"
}}]
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 

     - returns: RequestBuilder<Subscription> 
     */
    open class func getSubscriptionWithRequestBuilder(userId: String, deviceId: String, subscriptionId: String) -> RequestBuilder<Subscription> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{subscriptionId}", with: "\(subscriptionId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Subscription>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get all subscriptions for a device
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSubscriptions(userId: String, deviceId: String, completion: @escaping ((_ data: Subscriptions?,_ error: Error?) -> Void)) {
        getSubscriptionsWithRequestBuilder(userId: userId, deviceId: deviceId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get all subscriptions for a device
     - GET /users/{userId}/devices/{deviceId}/subscriptions
     - examples: [{contentType=application/json, example=""}]
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 

     - returns: RequestBuilder<Subscriptions> 
     */
    open class func getSubscriptionsWithRequestBuilder(userId: String, deviceId: String) -> RequestBuilder<Subscriptions> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Subscriptions>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
