//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class UserAPI: APIBase {
    /**
     Create device for a user
     
     - parameter userId: (path) The id (UUID) of the user for which to create a device. 
     - parameter device: (body) The device to be created for the user. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createDevice(userId: String, device: Device, completion: @escaping ((_ data: Device?,_ error: Error?) -> Void)) {
        createDeviceWithRequestBuilder(userId: userId, device: device).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create device for a user
     - POST /users/{userId}/devices
     - examples: [{contentType=application/json, example={
  "deviceType" : { },
  "createdAt" : 0,
  "name" : "aeiou",
  "id" : "aeiou",
  "updatedAt" : 6
}}]
     
     - parameter userId: (path) The id (UUID) of the user for which to create a device. 
     - parameter device: (body) The device to be created for the user. 

     - returns: RequestBuilder<Device> 
     */
    open class func createDeviceWithRequestBuilder(userId: String, device: Device) -> RequestBuilder<Device> {
        var path = "/users/{userId}/devices"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = device.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Device>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create a new location for a device
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 
     - parameter location: (body) Location to create for a device.  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createLocation(userId: String, deviceId: String, location: Location, completion: @escaping ((_ data: Location?,_ error: Error?) -> Void)) {
        createLocationWithRequestBuilder(userId: userId, deviceId: deviceId, location: location).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create a new location for a device
     - POST /users/{userId}/devices/{deviceId}/locations
     - examples: [{contentType=application/json, example={
  "createdAt" : 0,
  "altitude" : 5.962133916683182,
  "verticalAccuracy" : 2.3021358869347655,
  "latitude" : 6.027456183070403,
  "horizontalAccuracy" : 5.637376656633329,
  "longitude" : 1.4658129805029452
}}]
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 
     - parameter location: (body) Location to create for a device.  

     - returns: RequestBuilder<Location> 
     */
    open class func createLocationWithRequestBuilder(userId: String, deviceId: String, location: Location) -> RequestBuilder<Location> {
        var path = "/users/{userId}/devices/{deviceId}/locations"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = location.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Location>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create a publication for a device for a user
     
     - parameter userId: (path) The id (UUID) of the user to create a device for. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter publication: (body) Publication to create on a device.  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createPublication(userId: String, deviceId: String, publication: Publication, completion: @escaping ((_ data: Publication?,_ error: Error?) -> Void)) {
        createPublicationWithRequestBuilder(userId: userId, deviceId: deviceId, publication: publication).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create a publication for a device for a user
     - POST /users/{userId}/devices/{deviceId}/publications
     - examples: [{contentType=application/json, example={
  "duration" : 1.4658129805029452,
  "createdAt" : 0,
  "topic" : "aeiou",
  "range" : 6.027456183070403,
  "id" : "aeiou",
  "deviceId" : "aeiou",
  "properties" : {
    "key" : "aeiou"
  }
}}]
     
     - parameter userId: (path) The id (UUID) of the user to create a device for. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter publication: (body) Publication to create on a device.  

     - returns: RequestBuilder<Publication> 
     */
    open class func createPublicationWithRequestBuilder(userId: String, deviceId: String, publication: Publication) -> RequestBuilder<Publication> {
        var path = "/users/{userId}/devices/{deviceId}/publications"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = publication.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Publication>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create a subscription for a device for a user
     
     - parameter userId: (path) The id (UUID) of the user to create a device for.  
     - parameter deviceId: (path) The id (UUID) of the user device.  
     - parameter subscription: (body) Subscription to create on a device.  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createSubscription(userId: String, deviceId: String, subscription: Subscription, completion: @escaping ((_ data: Subscription?,_ error: Error?) -> Void)) {
        createSubscriptionWithRequestBuilder(userId: userId, deviceId: deviceId, subscription: subscription).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create a subscription for a device for a user
     - POST /users/{userId}/devices/{deviceId}/subscriptions
     - examples: [{contentType=application/json, example={
  "duration" : 1.4658129805029452,
  "createdAt" : 0,
  "topic" : "aeiou",
  "range" : 6.027456183070403,
  "selector" : "aeiou",
  "pushers" : [ "aeiou" ],
  "id" : "aeiou",
  "deviceId" : "aeiou"
}}]
     
     - parameter userId: (path) The id (UUID) of the user to create a device for.  
     - parameter deviceId: (path) The id (UUID) of the user device.  
     - parameter subscription: (body) Subscription to create on a device.  

     - returns: RequestBuilder<Subscription> 
     */
    open class func createSubscriptionWithRequestBuilder(userId: String, deviceId: String, subscription: Subscription) -> RequestBuilder<Subscription> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = subscription.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Subscription>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete an existing user's device
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteDevice(userId: String, deviceId: String, completion: @escaping ((_ error: Error?) -> Void)) {
        deleteDeviceWithRequestBuilder(userId: userId, deviceId: deviceId).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Delete an existing user's device
     - DELETE /users/{userId}/devices/{deviceId}
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 

     - returns: RequestBuilder<Void> 
     */
    open class func deleteDeviceWithRequestBuilder(userId: String, deviceId: String) -> RequestBuilder<Void> {
        var path = "/users/{userId}/devices/{deviceId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Delete a Publication
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter publicationId: (path) The id (UUID) of the subscription. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deletePublication(userId: String, deviceId: String, publicationId: String, completion: @escaping ((_ error: Error?) -> Void)) {
        deletePublicationWithRequestBuilder(userId: userId, deviceId: deviceId, publicationId: publicationId).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Delete a Publication
     - DELETE /users/{userId}/devices/{deviceId}/publications/{publicationId}
     - 
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter publicationId: (path) The id (UUID) of the subscription. 

     - returns: RequestBuilder<Void> 
     */
    open class func deletePublicationWithRequestBuilder(userId: String, deviceId: String, publicationId: String) -> RequestBuilder<Void> {
        var path = "/users/{userId}/devices/{deviceId}/publications/{publicationId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{publicationId}", with: "\(publicationId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Delete a Subscription
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteSubscription(userId: String, deviceId: String, subscriptionId: String, completion: @escaping ((_ error: Error?) -> Void)) {
        deleteSubscriptionWithRequestBuilder(userId: userId, deviceId: deviceId, subscriptionId: subscriptionId).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Delete a Subscription
     - DELETE /users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}
     - 
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 

     - returns: RequestBuilder<Void> 
     */
    open class func deleteSubscriptionWithRequestBuilder(userId: String, deviceId: String, subscriptionId: String) -> RequestBuilder<Void> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{subscriptionId}", with: "\(subscriptionId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Info about a device of a user
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDevice(userId: String, deviceId: String, completion: @escaping ((_ data: Device?,_ error: Error?) -> Void)) {
        getDeviceWithRequestBuilder(userId: userId, deviceId: deviceId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Info about a device of a user
     - GET /users/{userId}/devices/{deviceId}
     - examples: [{contentType=application/json, example={
  "deviceType" : { },
  "createdAt" : 0,
  "name" : "aeiou",
  "id" : "aeiou",
  "updatedAt" : 6
}}]
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 

     - returns: RequestBuilder<Device> 
     */
    open class func getDeviceWithRequestBuilder(userId: String, deviceId: String) -> RequestBuilder<Device> {
        var path = "/users/{userId}/devices/{deviceId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Device>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get all devices for a user
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDevices(userId: String, completion: @escaping ((_ data: Devices?,_ error: Error?) -> Void)) {
        getDevicesWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get all devices for a user
     - GET /users/{userId}/devices
     - examples: [{contentType=application/json, example=""}]
     
     - parameter userId: (path) The id (UUID) of the user of the device. 

     - returns: RequestBuilder<Devices> 
     */
    open class func getDevicesWithRequestBuilder(userId: String) -> RequestBuilder<Devices> {
        var path = "/users/{userId}/devices"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Devices>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get all devices of specified type for a user
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceType: (query) Type(s) to filter by 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDevicesByType(userId: String, deviceType: [DeviceType], completion: @escaping ((_ data: Devices?,_ error: Error?) -> Void)) {
        getDevicesByTypeWithRequestBuilder(userId: userId, deviceType: deviceType).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get all devices of specified type for a user
     - GET /users/{userId}/devices/findByType
     - examples: [{contentType=application/json, example=""}]
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceType: (query) Type(s) to filter by 

     - returns: RequestBuilder<Devices> 
     */
    open class func getDevicesByTypeWithRequestBuilder(userId: String, deviceType: [DeviceType]) -> RequestBuilder<Devices> {
        var path = "/users/{userId}/devices/findByType"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "deviceType": deviceType
        ])
        

        let requestBuilder: RequestBuilder<Devices>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Info about a publication on a device of a user
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter publicationId: (path) The id (UUID) of the publication. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPublication(userId: String, deviceId: String, publicationId: String, completion: @escaping ((_ data: Publication?,_ error: Error?) -> Void)) {
        getPublicationWithRequestBuilder(userId: userId, deviceId: deviceId, publicationId: publicationId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Info about a publication on a device of a user
     - GET /users/{userId}/devices/{deviceId}/publications/{publicationId}
     - examples: [{contentType=application/json, example={
  "duration" : 1.4658129805029452,
  "createdAt" : 0,
  "topic" : "aeiou",
  "range" : 6.027456183070403,
  "id" : "aeiou",
  "deviceId" : "aeiou",
  "properties" : {
    "key" : "aeiou"
  }
}}]
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter publicationId: (path) The id (UUID) of the publication. 

     - returns: RequestBuilder<Publication> 
     */
    open class func getPublicationWithRequestBuilder(userId: String, deviceId: String, publicationId: String) -> RequestBuilder<Publication> {
        var path = "/users/{userId}/devices/{deviceId}/publications/{publicationId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{publicationId}", with: "\(publicationId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Publication>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get all publications for a device
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPublications(userId: String, deviceId: String, completion: @escaping ((_ data: Publications?,_ error: Error?) -> Void)) {
        getPublicationsWithRequestBuilder(userId: userId, deviceId: deviceId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get all publications for a device
     - GET /users/{userId}/devices/{deviceId}/publications
     - examples: [{contentType=application/json, example=""}]
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 

     - returns: RequestBuilder<Publications> 
     */
    open class func getPublicationsWithRequestBuilder(userId: String, deviceId: String) -> RequestBuilder<Publications> {
        var path = "/users/{userId}/devices/{deviceId}/publications"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Publications>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Info about a subscription on a device of a user
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSubscription(userId: String, deviceId: String, subscriptionId: String, completion: @escaping ((_ data: Subscription?,_ error: Error?) -> Void)) {
        getSubscriptionWithRequestBuilder(userId: userId, deviceId: deviceId, subscriptionId: subscriptionId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Info about a subscription on a device of a user
     - GET /users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}
     - examples: [{contentType=application/json, example={
  "duration" : 1.4658129805029452,
  "createdAt" : 0,
  "topic" : "aeiou",
  "range" : 6.027456183070403,
  "selector" : "aeiou",
  "pushers" : [ "aeiou" ],
  "id" : "aeiou",
  "deviceId" : "aeiou"
}}]
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter subscriptionId: (path) The id (UUID) of the subscription. 

     - returns: RequestBuilder<Subscription> 
     */
    open class func getSubscriptionWithRequestBuilder(userId: String, deviceId: String, subscriptionId: String) -> RequestBuilder<Subscription> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions/{subscriptionId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{subscriptionId}", with: "\(subscriptionId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Subscription>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get all subscriptions for a device
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSubscriptions(userId: String, deviceId: String, completion: @escaping ((_ data: Subscriptions?,_ error: Error?) -> Void)) {
        getSubscriptionsWithRequestBuilder(userId: userId, deviceId: deviceId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get all subscriptions for a device
     - GET /users/{userId}/devices/{deviceId}/subscriptions
     - examples: [{contentType=application/json, example=""}]
     
     - parameter userId: (path) The id (UUID) of the user. 
     - parameter deviceId: (path) The id (UUID) of the device. 

     - returns: RequestBuilder<Subscriptions> 
     */
    open class func getSubscriptionsWithRequestBuilder(userId: String, deviceId: String) -> RequestBuilder<Subscriptions> {
        var path = "/users/{userId}/devices/{deviceId}/subscriptions"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Subscriptions>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Info about a user
     
     - parameter userId: (path) The id (UUID) of the user to retrieve. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUser(userId: String, completion: @escaping ((_ data: Users?,_ error: Error?) -> Void)) {
        getUserWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Info about a user
     - GET /users/{userId}
     - examples: [{contentType=application/json, example=""}]
     
     - parameter userId: (path) The id (UUID) of the user to retrieve. 

     - returns: RequestBuilder<Users> 
     */
    open class func getUserWithRequestBuilder(userId: String) -> RequestBuilder<Users> {
        var path = "/users/{userId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Users>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Trigger the proximity event between a device and a ranged BLE iBeacon
     
     - parameter userId: (path) The id (UUID) of the user for which to trigger a proximity event. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter proximityEvent: (body) The proximity event to be created for the user. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func triggerProximityEvents(userId: String, deviceId: String, proximityEvent: ProximityEvent, completion: @escaping ((_ data: ProximityEvent?,_ error: Error?) -> Void)) {
        triggerProximityEventsWithRequestBuilder(userId: userId, deviceId: deviceId, proximityEvent: proximityEvent).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Trigger the proximity event between a device and a ranged BLE iBeacon
     - POST /users/{userId}/devices/{deviceId}/proximityEvents
     - examples: [{contentType=application/json, example={
  "createdAt" : 0,
  "distance" : 6.027456183070403,
  "id" : "aeiou",
  "deviceId" : "aeiou"
}}]
     
     - parameter userId: (path) The id (UUID) of the user for which to trigger a proximity event. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter proximityEvent: (body) The proximity event to be created for the user. 

     - returns: RequestBuilder<ProximityEvent> 
     */
    open class func triggerProximityEventsWithRequestBuilder(userId: String, deviceId: String, proximityEvent: ProximityEvent) -> RequestBuilder<ProximityEvent> {
        var path = "/users/{userId}/devices/{deviceId}/proximityEvents"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = proximityEvent.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ProximityEvent>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Update an existing device
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter device: (body) Device object that needs to be updated 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateDevice(userId: String, deviceId: String, device: Device, completion: @escaping ((_ error: Error?) -> Void)) {
        updateDeviceWithRequestBuilder(userId: userId, deviceId: deviceId, device: device).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Update an existing device
     - POST /users/{userId}/devices/{deviceId}
     
     - parameter userId: (path) The id (UUID) of the user of the device. 
     - parameter deviceId: (path) The id (UUID) of the user device. 
     - parameter device: (body) Device object that needs to be updated 

     - returns: RequestBuilder<Void> 
     */
    open class func updateDeviceWithRequestBuilder(userId: String, deviceId: String, device: Device) -> RequestBuilder<Void> {
        var path = "/users/{userId}/devices/{deviceId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{deviceId}", with: "\(deviceId)", options: .literal, range: nil)
        let URLString = AlpsAPI.basePath + path
        let parameters = device.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = AlpsAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
