//
// APIError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class APIError: Codable {

    public var code: Int32?
    public var message: String?

    public init() {}

}
