//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A device might be either virtual like a pin device or physical like a mobile phone or iBeacon device.  */
open class Device: JSONEncodable {

    /** The id (UUID) of the device. */
    public var id: String?
    /** The name of the device. */
    public var name: String?
    public var deviceType: DeviceType?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["deviceType"] = self.deviceType?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
