//
// DeviceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum DeviceType: String {
    case mobileDevice = "MobileDevice"
    case pinDevice = "PinDevice"
    case beaconDevice = "BeaconDevice"

    func encodeToJSON() -> Any { return self.rawValue }
}
