//
// DeviceLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class DeviceLocation: JSONEncodable {

    /** The id (UUID) of the device to create a device location for.  */
    public var deviceId: String?
    public var location: Location?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["deviceId"] = self.deviceId
        nillableDictionary["location"] = self.location?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
