//
// SimpleLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SimpleLocation: JSONEncodable {

    /** The latitude of the device in degrees, for instance &#39;46.5333&#39; (Lausanne, Switzerland).  */
    public var latitude: Double?
    /** The longitude of the device in degrees, for instance &#39;6.6667&#39; (Lausanne, Switzerland).  */
    public var longitude: Double?
    /** The altitude of the device in meters, for instance &#39;495.0&#39; (Lausanne, Switzerland).  */
    public var altitude: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["altitude"] = self.altitude

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
