//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Device: JSONEncodable {
    /** The id (UUID) of the device */
    public var deviceId: String?
    /** The name of the device */
    public var name: String?
    /**  The platform of the device, this can be any string representing the platform type, for instance &#39;iOS&#39;  */
    public var platform: String?
    /**  The deviceToken is the device push notification token given to this device by the OS, either iOS or Android for identifying the device with push notification services.  */
    public var deviceToken: String?
    public var location: Location?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["deviceId"] = self.deviceId
        nillableDictionary["name"] = self.name
        nillableDictionary["platform"] = self.platform
        nillableDictionary["deviceToken"] = self.deviceToken
        nillableDictionary["location"] = self.location?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
