//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Device: JSONEncodable {
    /** The id (UUID) of the device */
    public var deviceId: String?
    /** The name of the device */
    public var name: String?
    /** The platform of the device, this can be any string representing the platform type, for instance &#39;iOS&#39; */
    public var platform: String?
    /** The deviceToken is the device &#39;real&#39; id. For instance, each phone has it&#39;s own identifer that can be set here. Please note that this particular id is independant from the object id */
    public var deviceToken: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["deviceId"] = self.deviceId
        nillableDictionary["name"] = self.name
        nillableDictionary["platform"] = self.platform
        nillableDictionary["deviceToken"] = self.deviceToken
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
