//
// Match.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object representing a match between a subscription and a publication. */
open class Match: JSONEncodable {
    /** The id (UUID) of the user */
    public var matchId: String?
    /** The timestamp of the match in seconds since Jan 01 1970 (UTC). */
    public var timestamp: Int64?
    public var publication: Publication?
    public var subscription: Subscription?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["matchId"] = self.matchId
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        nillableDictionary["publication"] = self.publication?.encodeToJSON()
        nillableDictionary["subscription"] = self.subscription?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
